### ISSUE TITLE
Pictures are out of the repo

### ISSUE THREAD

**Issue by frames75** [Tereshka/pic-some-app#1]
I cloned this repo in hopes of seeing how to managing public assets like pictures with the react-router package. However, all the pictures files of the repo are useless cause the code aims to the url of these particular repo, not the installed. If this repo is delete, all cloned repos will fail.

That's ugly.

**Comment by Tereshka** [comment]
good day @frames75

I'm using a simple json file (https://github.com/Tereshka/pic-some-app/blob/master/src/data/images.json) which only **emulates the real answer from server's database**. irl it can be a response with different items. I'm using pictures as my goods, so they should be saved somewhere on the server. That's why those images are not supposed to be saved in `public` or smth else folder, which will be accessible from a client. As I don't have server I use paths from my repo. 

You may add any changes as you wish and update your fork as you want to received **_your_** suspected behaviour
